apiVersion: apps/v1
kind: Deployment
metadata:
  name: hyeboard-api
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hyeboard-automation-worker
spec:
  replicas: 1
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hyeboard-api
spec:
  minReplicas: 1
  maxReplicas: 2
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hyeboard-automation-worker
spec:
  minReplicas: 1
  maxReplicas: 2
