apiVersion: v1
kind: Service
metadata:
  name: hyeboard-browserless
  labels:
    app.kubernetes.io/name: hyeboard-browserless
    app.kubernetes.io/component: browserless
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 3000
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: hyeboard-browserless
    app.kubernetes.io/component: browserless
