{{- if .Values.serviceAccounts.api.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "hyeboard.apiServiceAccountName" . }}
  labels:
    {{- include "hyeboard.labels" . | nindent 4 }}
    app.kubernetes.io/name: {{ include "hyeboard.apiName" . }}
    app.kubernetes.io/component: api
    {{- include "hyeboard.commonLabels" . | nindent 4 }}
  {{- with .Values.serviceAccounts.api.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: false
{{- end }}
{{- if .Values.serviceAccounts.automationWorker.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "hyeboard.automationWorkerServiceAccountName" . }}
  labels:
    {{- include "hyeboard.labels" . | nindent 4 }}
    app.kubernetes.io/name: {{ include "hyeboard.automationWorkerName" . }}
    app.kubernetes.io/component: automation-worker
    {{- include "hyeboard.commonLabels" . | nindent 4 }}
  {{- with .Values.serviceAccounts.automationWorker.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: false
{{- end }}
