apiVersion: apps/v1
kind: Deployment
metadata:
  name: hyeboard-api
spec:
  replicas: 2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hyeboard-automation-worker
spec:
  replicas: 2
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hyeboard-api
spec:
  minReplicas: 2
  maxReplicas: 6
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hyeboard-automation-worker
spec:
  minReplicas: 2
  maxReplicas: 4
